namespace IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection
{
	/// <summary>
	/// <section name="dates-section" type="IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.ExampleSection, IndependentUtils.Configuration.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
	/// </summary>
	[IndependentUtils.Configuration.Attributes.SectionName("dates-section")]
	public class ExampleSection : System.Configuration.ConfigurationSection, IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.IExampleSection
	{
		public virtual System.String Name
		{
			get
			{
				return NameAux;
			}
		}

		[System.Configuration.ConfigurationProperty("name")]
		public virtual System.String NameAux
		{
			get
			{
				return (System.String)this["name"];
			}
			set
			{
				this["name"] = value;
			}
		}

		public virtual System.Collections.Generic.IEnumerable<IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.IDateElement> ImportantDates
		{
			get
			{
				return ImportantDatesAux;
			}
		}

		[System.Configuration.ConfigurationProperty("important-dates", IsRequired = true)]
		[System.Configuration.ConfigurationCollection(typeof(IndependentUtils.Configuration.ConfigurationElementCollection<DateElement>), AddItemName = "date")]
		public virtual IndependentUtils.Configuration.ConfigurationElementCollection<DateElement> ImportantDatesAux
		{
			get
			{
				return (IndependentUtils.Configuration.ConfigurationElementCollection<DateElement>)this["important-dates"];
			}
		}

		public virtual System.Collections.Generic.IEnumerable<IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.IDateElement> MandatoryDates
		{
			get
			{
				return MandatoryDatesAux;
			}
		}

		[System.Configuration.ConfigurationProperty("mandatory-dates", IsRequired = true)]
		[System.Configuration.ConfigurationCollection(typeof(IndependentUtils.Configuration.ConfigurationElementCollection<DateElement>), AddItemName = "date")]
		public virtual IndependentUtils.Configuration.ConfigurationElementCollection<DateElement> MandatoryDatesAux
		{
			get
			{
				return (IndependentUtils.Configuration.ConfigurationElementCollection<DateElement>)this["mandatory-dates"];
			}
		}

		public virtual IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.ITimeFormatOptions TimeFormats
		{
			get
			{
				return TimeFormatsAux;
			}
		}

		[System.Configuration.ConfigurationProperty("time-formats", IsRequired = true)]
		public virtual TimeFormatOptions TimeFormatsAux
		{
			get
			{
				return (TimeFormatOptions)this["time-formats"];
			}
			set
			{
				this["time-formats"] = value;
			}
		}

	}

	public class DateElement : System.Configuration.ConfigurationElement, IndependentUtils.Configuration.IKeyd, IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.IDateElement
	{
		/// <summary>
		///		A simple function that generates the DateElement's key from
		///		the provided lambda, so that it can be consumed by the
		///		other property.
		/// </summary>
		public virtual System.Func<DateElement, System.Object> DateElementKeyFunc
		{
			get
			{
				return t => new System.DateTime(t.Year, t.Month, t.Day);
			}
		}

		public virtual System.Object Key
		{
			get
			{
				return DateElementKeyFunc(this);
			}
		}

		public virtual System.Int32 Day
		{
			get
			{
				return DayAux;
			}
		}

		[System.Configuration.ConfigurationProperty("day", IsRequired = true)]
		public virtual System.Int32 DayAux
		{
			get
			{
				return (System.Int32)this["day"];
			}
			set
			{
				this["day"] = value;
			}
		}

		public virtual System.Int32 Month
		{
			get
			{
				return MonthAux;
			}
		}

		[System.Configuration.ConfigurationProperty("month", IsRequired = true)]
		public virtual System.Int32 MonthAux
		{
			get
			{
				return (System.Int32)this["month"];
			}
			set
			{
				this["month"] = value;
			}
		}

		public virtual System.Int32 Year
		{
			get
			{
				return YearAux;
			}
		}

		[System.Configuration.ConfigurationProperty("year", IsRequired = true)]
		public virtual System.Int32 YearAux
		{
			get
			{
				return (System.Int32)this["year"];
			}
			set
			{
				this["year"] = value;
			}
		}

	}

	public class TimeFormatOptions : System.Configuration.ConfigurationElement, IndependentUtils.Configuration.IKeyd, IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.ITimeFormatOptions
	{
		/// <summary>
		///		A simple function that generates the TimeFormatOptions's key
		///		from the provided lambda, so that it can be consumed by the
		///		other property.
		/// </summary>
		public virtual System.Func<TimeFormatOptions, System.Object> TimeFormatOptionsKeyFunc
		{
			get
			{
				return t => new System.Object();
			}
		}

		public virtual System.Object Key
		{
			get
			{
				return TimeFormatOptionsKeyFunc(this);
			}
		}

		public virtual System.String Format
		{
			get
			{
				return FormatAux;
			}
		}

		[System.Configuration.ConfigurationProperty("format", IsRequired = true)]
		public virtual System.String FormatAux
		{
			get
			{
				return (System.String)this["format"];
			}
			set
			{
				this["format"] = value;
			}
		}

		public virtual System.Boolean IsLocal
		{
			get
			{
				return IsLocalAux;
			}
		}

		[System.Configuration.ConfigurationProperty("is-local", DefaultValue = true)]
		public virtual System.Boolean IsLocalAux
		{
			get
			{
				return (System.Boolean)this["is-local"];
			}
			set
			{
				this["is-local"] = value;
			}
		}

	}

}
