//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
namespace IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection
{
	/*
	 *
	 * Add the following line to your config sections:
	 *
	 * <section name="dates-section" type="IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.ExampleSection, IndependentUtils.Configuration.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"/>
	 *
	 */
	[IndependentUtils.Configuration.Attributes.SectionName("dates-section")]
	public partial class ExampleSection : System.Configuration.ConfigurationSection,
		IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.IExampleSection
    {
		public const string NameTag = "name";
		
		[System.Configuration.ConfigurationProperty(NameTag)]
		protected virtual System.String NameAux 
		{
			get
			{
				return (System.String)this[NameTag];
			}
			set
			{
				this[NameTag] = value;
			}
		}

		public virtual System.String Name 
		{
			get
			{
				return NameAux;
			}
		}
		public const string TimeFormatsTag = "time-formats";
		
		[System.Configuration.ConfigurationProperty(TimeFormatsTag, IsRequired = true)]
		protected virtual TimeFormatOptions TimeFormatsAux 
		{
			get
			{
				return (TimeFormatOptions)this[TimeFormatsTag];
			}
			set
			{
				this[TimeFormatsTag] = value;
			}
		}

		public virtual IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.ITimeFormatOptions TimeFormats 
		{
			get
			{
				return TimeFormatsAux;
			}
		}
		
		public const string ImportantDatesTag = "important-dates";
		
		[System.Configuration.ConfigurationProperty(ImportantDatesTag, IsRequired = true)]
        [System.Configuration.ConfigurationCollection(typeof(IndependentUtils.Configuration.ConfigurationElementCollection<DateElement>), AddItemName = "add")]
		protected virtual IndependentUtils.Configuration.ConfigurationElementCollection<DateElement> ImportantDatesAux
		{
			get
			{
				return (IndependentUtils.Configuration.ConfigurationElementCollection<DateElement>)this[ImportantDatesTag];
			}
		}

		public virtual System.Collections.Generic.IEnumerable<IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.IDateElement> ImportantDates
		{
			get
			{
				return ImportantDatesAux;
			}
		}
		
		public const string MandatoryDatesTag = "mandatory-dates";
		
		[System.Configuration.ConfigurationProperty(MandatoryDatesTag, IsRequired = true)]
        [System.Configuration.ConfigurationCollection(typeof(IndependentUtils.Configuration.ConfigurationElementCollection<DateElement>), AddItemName = "add")]
		protected virtual IndependentUtils.Configuration.ConfigurationElementCollection<DateElement> MandatoryDatesAux
		{
			get
			{
				return (IndependentUtils.Configuration.ConfigurationElementCollection<DateElement>)this[MandatoryDatesTag];
			}
		}

		public virtual System.Collections.Generic.IEnumerable<IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.IDateElement> MandatoryDates
		{
			get
			{
				return MandatoryDatesAux;
			}
		}
	}

	public partial class DateElement : System.Configuration.ConfigurationElement, 
		IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.IDateElement, 
		IndependentUtils.Configuration.IKeyd
	{
		private static readonly System.Func<DateElement, object> GetKeyFunc = t => new System.DateTime(t.Year, t.Month, t.Day);
		public virtual System.Object Key => GetKeyFunc(this);
		public const string DayTag = "day";
		
		[System.Configuration.ConfigurationProperty(DayTag, IsRequired = true)]
		protected virtual System.Int32 DayAux 
		{
			get
			{
				return (System.Int32)this[DayTag];
			}
			set
			{
				this[DayTag] = value;
			}
		}

		public virtual System.Int32 Day 
		{
			get
			{
				return DayAux;
			}
		}
		public const string MonthTag = "month";
		
		[System.Configuration.ConfigurationProperty(MonthTag, IsRequired = true)]
		protected virtual System.Int32 MonthAux 
		{
			get
			{
				return (System.Int32)this[MonthTag];
			}
			set
			{
				this[MonthTag] = value;
			}
		}

		public virtual System.Int32 Month 
		{
			get
			{
				return MonthAux;
			}
		}
		public const string YearTag = "year";
		
		[System.Configuration.ConfigurationProperty(YearTag, IsRequired = true)]
		protected virtual System.Int32 YearAux 
		{
			get
			{
				return (System.Int32)this[YearTag];
			}
			set
			{
				this[YearTag] = value;
			}
		}

		public virtual System.Int32 Year 
		{
			get
			{
				return YearAux;
			}
		}
	}

	public partial class TimeFormatOptions : System.Configuration.ConfigurationElement, 
		IndependentUtils.Configuration.IntegrationTests.AutogeneratedSection.ITimeFormatOptions, 
		IndependentUtils.Configuration.IKeyd
	{
		private static readonly System.Func<TimeFormatOptions, object> GetKeyFunc = t => new System.Object();
		public virtual System.Object Key => GetKeyFunc(this);
		public const string FormatTag = "format";
		
		[System.Configuration.ConfigurationProperty(FormatTag, IsRequired = true)]
		protected virtual System.String FormatAux 
		{
			get
			{
				return (System.String)this[FormatTag];
			}
			set
			{
				this[FormatTag] = value;
			}
		}

		public virtual System.String Format 
		{
			get
			{
				return FormatAux;
			}
		}
		public const string IsLocalTag = "is-local";
		
		[System.Configuration.ConfigurationProperty(IsLocalTag, DefaultValue = true)]
		protected virtual System.Boolean IsLocalAux 
		{
			get
			{
				return (System.Boolean)this[IsLocalTag];
			}
			set
			{
				this[IsLocalTag] = value;
			}
		}

		public virtual System.Boolean IsLocal 
		{
			get
			{
				return IsLocalAux;
			}
		}
	}

}
